internal/store/plugin.go
internal/store/plugin_test.go

Very rudimentary support for filtering plugins via the `filter` query string parameter.
Note that paging already existed. We'll defer worrying about the Mattermost server version for now.
https://mattermost.atlassian.net/browse/MM-17544

support filtering plugins

---

cmd/marketplace/main.go

Remove the `RunE` declaration for the root command so that invoking without the `server` subcommand just displays the help. At the moment, there is only the single subcommand, but in the future this will likely include CLI-related subcommands.

Fix default invocation

---

internal/api/client.go
internal/api/client_test.go

Duplicates changes from https://github.com/mattermost/mattermost-server/pull/13273

Handle trailing slash when building marketplace api path

---

cmd/generator/add.go
cmd/generator/main.go
go.mod
go.sum

This PR add a `generator add` command, which is used to add community plugins to the Marketplace Database.
To update the database you would e.g. run `go run ./cmd/generator/ add matterpoll v1.5.0 | jq | sponge plugins.json`.
I did a lot of refactoring in `cmd/generator/main.go` to keep the code DRY. I've rebuild the database from scratch and there was no difference to the existing one. Hence, I'm confident, I didn't add a regression.
I've tested the changes by downloading the release from https://github.com/hanzei/plugin-test/releases/tag/v1.4.0. The generated changed to the database can be found below.
`release_notes_url` is not set, because there is not mechanism in the manifest to define it and we can't rely on the GitHub URL, as the repo might not be located at GitHub.
`signature` is …

Add generator add command

---

Makefile

The Marketplace gets deployed as a aws lambda function. Because of this, we can only deploy a single binary and no additional files. The Marketplace uses `plugins.json` to store all available plugins, which we can't deploy to aws. To resolve this issue, `github.com/rakyll/statik` get used, which transforms `plugins.json` into a variable that gets build into the binary. You can find it in `data/statik/statik.go`. The CI makes sure that `data/statik/statik.go` gets updated every time, by re-generating it and checking if there are un committed changes. 
A new version `v0.1.7` of `github.com/rakyll/statik` was released a few days ago. The latest version did change the way the files are generated. This caused build failures like https://app.circleci.com/jobs/github/mattermost/mattermost-marketp …

Pin github.com/rakyll/statik version

---

internal/model/plugin.go
internal/model/plugin_test.go

This make the `json` output a bit nicer. Forgot about the case in https://github.com/mattermost/mattermost-marketplace/pull/42
https://mattermost.atlassian.net/browse/MM-23184

[MM-23184] Omit empty labels list

---

.circleci/config.yml
Makefile

`sls` wasn't working on `master`, so I've fixed to use the `serverless` name instead. Confirmed a successful deploy via `master`.
The commit history here is noisy, since I'm basically just merging `master` to `production`, and the merge commit there wasn't part of the tree that Git was expecting. The actual delta of code, however, is up-to-date.

Fix production

---

.circleci/config.yml

Don't use go cache for building the binary.
https://community-daily.mattermost.com/private-core/pl/pac41yhnsfyp8pobgc44j38x5h

Don't use go cache

---

.circleci/config.yml

`serverless` will not soon not longer work with node < v10. (https://www.serverless.com/framework/docs/deprecations/#OUTDATED_NODEJS) Update the node version to the latest LTS version.
I've tested the changes by deploying to staging.

Bump node version for deploy job

---

Makefile
README.md

`generator add` should be used to add releases for all not predefined plugins. This PR updated the documentation to make this clear.
Fixes https://github.com/mattermost/mattermost-marketplace/issues/74

Update docs on how to add new releases

---

.circleci/config.yml

See the issue description for more infos.
I've tested the command locally and it does correctly install `v1.83.0`. Will cherry-pick the change once it's merged to unblock the deployments.
Fixes https://github.com/mattermost/mattermost-marketplace/issues/118

Always use a <2.0.0 version of serverless

---

cmd/generator/add.go
cmd/generator/bundles.go
cmd/generator/main.go
go.mod
go.sum

https://github.com/mattermost/mattermost-marketplace/commit/bad8dfc4e7bbe13660ac4d72bcd040cb58702b20  makes the migration command run all the DB file migrations concurrently.
https://github.com/mattermost/mattermost-marketplace/commit/4d3d8612e7d80b36595ecfa537088ad7387804d4 ensure the log level is send consistently for all commands and log the message that is triggered when a platform-specific bundle is not found to `Debug`.
https://mattermost.atlassian.net/browse/MM-30263

Run Marketplace migration commend concurrently

---

CONTRIBUTING.md

New plugins should get added to Looker so we can track there telemetry. This PR adds a step to the release checklist to ensure this gets done.
None

Add notice about Looker to plugin checklist

---

.circleci/config.yml
internal/api/plugins.go
internal/model/plugin.go
internal/store/static.go
internal/store/static_test.go

`golangci-lint` v1.33.2 is the default version used in most Mattermost repositories. This repo used a quite old version which missed some issues.
The PR also makes use of an orb instead of implementing the golangci-lint command itself.
https://mattermost.atlassian.net/browse/MM-32593

[MM-32593] Update golangci-lint to v1.33.2

---

internal/model/label.go

Should it be "E20 and Cloud" or "Cloud and E20"?
https://mattermost.atlassian.net/browse/MM-32278

[MM-32278] Change "E20 Only" tag on listings to "E20 and Cloud"

---

plugins.json

This PR adds the `focalboard` plugin at its `v0.7.0` to the cloud marketplace only.
[Focalboard card](https://focalboard-community.octo.mattermost.com/workspace/qgsck6cts3fwpqwyjiupjm5cde?id=47aa9bb4-6967-4a96-83c7-11bd6b20f1eb&v=ca1a5441-4c1c-4d0e-856e-88cc744576c8&c=c55018cc-2c13-482e-8f79-203946bfaa94)

Add the focalboard plugin version v0.7.0 to the cloud marketplace

---

plugins.json

Add v1.14.2, the first release that is not enterprise-only.
https://mattermost.atlassian.net/browse/MM-36666

Add v1.14.2 of mattermost-plugin-incident-collaboration to the Marketplace

---

plugins.json

Plugin cut using Matterbuild with
```
/mb cutplugin --repo mattermost-plugin-incident-collaboration --tag v1.15.1-alpha.1 --pre-release --commitSHA 66c9ee4b66a3caa570ae4c2d7cb3a38d10f7de7b
```
Changes to the Marketplace here generated with
```
go run ./cmd/generator/ add mattermost-plugin-incident-collaboration v1.15.1-alpha.1 --official --beta
```

Add v1.15.1-alpha.1 of Incident Collaboration to the Marketplace

---

plugins.json

- Plugin was cut with `/mb cutplugin --repo mattermost-plugin-incident-collaboration --tag v1.15.1-alpha.2 --pre-release --commitSHA ae8ae1965073ebe101a075e977ecd916d3bde0e0`
- Changes to marketplace generated with `go run ./cmd/generator/ add mattermost-plugin-incident-collaboration v1.15.1-alpha.2 --official --beta`

Add v1.15.1-alpha.2 of mattermost-plugin-incident-collaboration

---

plugins.json

- cut with `/mb cutplugin --repo mattermost-plugin-incident-collaboration --tag v1.15.1-alpha.4 --pre-release --commitSHA e5bf18ccd4748c98dfccf5ea4c3e221b63a24c93`
- this commit made with: `go run ./cmd/generator/ add mattermost-plugin-incident-collaboration v1.15.1-alpha.4 --official --beta`

Add v1.15.1-alpha.4 of mattermost-plugin-incident-collaboration to private-beta

---

plugins.json

- cut with `/mb cutplugin --repo mattermost-plugin-incident-collaboration --tag v1.15.1-alpha.3 --pre-release --commitSHA d6c2595ff90a99221ce62158e41ebc0592f9877b`
- this commit made with `go run ./cmd/generator/ add mattermost-plugin-incident-collaboration v1.15.1-alpha.3 --official --beta`

Add v1.15.1-alpha.3 of mattermost-plugin-incident-collaboration to private-beta

---

plugins.json

Publish Focalboard plugin v0.8.2 to the Marketplace for Cloud only.
I plan to merge this PR instead of the one for v0.8.1 (#208).

Add v0.8.2 of focalboard to the Marketplace

---

plugins.json

As spotted by @hanzei, we needed a new Marketplace release of the channel export plugin.
--

Add v1.0.0 of mattermost-plugin-channel-export to the Marketplace

---

plugins.json

Due to a client-side issue in 0.5.0, we are reverting this release as it is causing issues with websocket connections. This is fixed with https://github.com/mattermost/mattermost-plugin-todo/pull/156, but to be timely and to minimize the possibility of having other customers run into this issue, we are also reverting this version.
https://github.com/mattermost/mattermost-plugin-todo/issues/155

Revert todo 0.5.0 entry

---

plugins.json

- cut with `/mb cutplugin --repo mattermost-plugin-calls --tag v0.4.2 --pre-release --commitSHA 892ddeda5fc0c4e143cf31a8ad2aaf2c21761cdb`
- this commit made with `go run ./cmd/generator/ add mattermost-plugin-calls v0.4.2 --official --beta`

Add v0.4.2 of mattermost-plugin-calls to the Marketplace

---

plugins.json

- cut with `/mb cutplugin --repo mattermost-plugin-calls --tag v0.4.3 --pre-release --commitSHA a74a92bb7a1430813579618c8568a946f01607c9`
- this commit made with `go run ./cmd/generator/ add mattermost-plugin-calls v0.4.3 --official --beta `
- none

Add v0.4.3 of mattermost-plugin-calls to the Marketplace

---

plugins.json

- cut with `/mb cutplugin --repo mattermost-plugin-calls --tag v0.4.4 --pre-release --commitSHA e2ffece5808ff85a20ebd724c77cd8903322653a`
- this commit made with `go run ./cmd/generator/ add mattermost-plugin-calls v0.4.4 --official --beta`
- none

Add v0.4.4 of mattermost-plugin-calls to the Marketplace

---

plugins.json

- cut with `/mb cutplugin --repo mattermost-plugin-calls --tag v0.4.5 --pre-release --commitSHA 6e94eb61373a40418d248112d809c231bdaef30b`
- this commit made with `go run ./cmd/generator/ add mattermost-plugin-calls v0.4.5 --official --beta `
- none

Add v0.4.5 of mattermost-plugin-calls to the Marketplace

---

plugins.json

- cut with `/mb cutplugin --repo mattermost-plugin-calls --tag v0.4.8 --pre-release`
- this commit made with `go run ./cmd/generator/ add mattermost-plugin-calls v0.4.8 --official --beta `
- none

Add v0.4.8 of mattermost-plugin-calls to the production Marketplace

---

plugins.json

- Calls is only available for on-prem installations at the moment.
- I think this should be all we need, @hanzei can you confirm?
- https://mattermost.atlassian.net/browse/MM-43497

MM-43497 - Add on-prem label to marketplace calls plugin

---

plugins.json

- cut with `/mb cutplugin --repo mattermost-plugin-calls --tag v0.4.9 --pre-release`
- this commit made with `go run ./cmd/generator/ add mattermost-plugin-calls v0.4.9 --official --beta --on-prem`
- none

Add v0.4.9 of mattermost-plugin-calls to the Production Marketplace

---

plugins.json

- originally cut with `/mb cutplugin --repo mattermost-plugin-calls --tag v0.5.0 --pre-release` but failed in signing
- cut with `/mb cutplugin --repo mattermost-plugin-calls --tag v0.5.1 --pre-release` -- but the tag and version don't match. Should be fine.
- this commit made with `go run ./cmd/generator/ add mattermost-plugin-calls v0.5.1 --official --beta --on-prem`
- none

Add v0.5.1/v0.5.0 of mattermost-plugin-calls to the Marketplace

---

go.mod
go.sum
plugins.json

- cut with `/mb cutplugin --repo mattermost-plugin-calls --tag v0.5.3 --pre-release`
- this commit made with `go run ./cmd/generator/ add mattermost-plugin-calls v0.5.3 --official --beta --on-prem`
- had some trouble with `x/sys` -- needed to be upgraded
- none

Add v0.5.3 of mattermost-plugin-calls to the Marketplace

---

plugins.json

Changelog at https://github.com/mattermost/mattermost-plugin-todo/releases/tag/v0.6.0
--

Add v0.6.0 of mattermost-plugin-todo to the Marketplace

---

plugins.json

Generated with `go run ./cmd/generator/ add mattermost-plugin-zoom v1.6.0 --official --on-prem`.
Changelist at https://github.com/mattermost/mattermost-plugin-zoom/releases/tag/v1.6.0.
--

Add v1.6.0 of mattermost-plugin-zoom to the Marketplace

---

plugins.json

Generated with `go run ./cmd/generator/ add mattermost-plugin-zoom v1.6.0-cloud --official --cloud`.
Changelist at https://github.com/mattermost/mattermost-plugin-zoom/releases/tag/v1.6.0-cloud.
--

Add v1.6.0-cloud of mattermost-plugin-zoom to the Marketplace

---

plugins.json

Something went wrong with the signatures added in https://github.com/mattermost/mattermost-marketplace/pull/287. Not entirely sure what the cause is, but the changes in this PR make it so it installs properly.
Steps taken to produce this PR:
- Manually remove `1.6.0` entry from `plugins.json` (first commit of this PR)
- Add `1.6.0` entry via the `./cmd/generator add` command as usual
Fixes https://github.com/mattermost/mattermost-plugin-zoom/issues/265
Fixes https://github.com/mattermost/mattermost-plugin-zoom/issues/266

Re-add v1.6.0 of mattermost-plugin-zoom to the Marketplace

---

plugins.json

- This is for testing the cloud free trial changes in https://github.com/mattermost/mattermost-plugin-calls/pull/105 That's why it's `"hosting": "cloud"`
- Will be reverted as soon as testing is done
- none

Add v0.6.1-alpha2 of mattermost-plugin-calls to the Marketplace

---

plugins.json

- cut with `/mb cutplugin --repo mattermost-plugin-calls --tag v0.6.1--pre-release`
- this commit made with `go run ./cmd/generator/ add mattermost-plugin-calls v0.6.1 --official --beta`
- none

Add v0.6.1 of mattermost-plugin-calls to the Marketplace

---

plugins.json

- cut with `/mb cutplugin --repo mattermost-plugin-calls --tag v0.7.0 --pre-release`
- this commit made with `go run ./cmd/generator/ add mattermost-plugin-calls v0.7.0 --official --beta`
- none

Add v0.7.0 of mattermost-plugin-calls to the Marketplace

---

plugins.json

- cut with `/mb cutplugin --repo mattermost-plugin-calls --tag v0.7.1 --pre-release`
- this commit made with `go run ./cmd/generator/ add mattermost-plugin-calls v0.7.1 --official --beta`
- none

Add v0.7.1 of mattermost-plugin-calls to the Marketplace

---

plugins.json

- cut with `/mb cutplugin --repo mattermost-plugin-calls --tag v0.8.1 --pre-release`
- this commit made with `go run ./cmd/generator/ add mattermost-plugin-calls v0.8.1 --official --beta`
- https://mattermost.atlassian.net/browse/MM-46421

MM-46421 - Add v0.8.1 of mattermost-plugin-calls to the Marketplace

---

plugins.json

This PR is for adding version `v1.5.0` of the Gitlab plugin to the Mattermost marketplace.
Fixes https://github.com/mattermost/mattermost-plugin-gitlab/issues/274

Add v1.5.0 of mattermost-plugin-gitlab to the Marketplace

---

plugins.json

- cut with `/mb cutplugin --repo mattermost-plugin-calls --tag v0.9.0`
- this commit made with `go run ./cmd/generator/ add mattermost-plugin-calls v0.9.0 --official --beta`
- https://mattermost.atlassian.net/browse/MM-46421

MM-47037 - Add mattermost plugin calls v0.9.0 to the marketplace

---

plugins.json

- cut with `/mb cutplugin --repo mattermost-plugin-calls --tag v0.11.0`
- this commit made with `go run ./cmd/generator/ add mattermost-plugin-calls v0.10.0 --official`
- https://mattermost.atlassian.net/browse/MM-48476

MM-48476 - Add v0.11.0 of mattermost-plugin-calls to the Marketplace

---

plugins.json

- NOTE: I had to do this kind of manually -- the marketplace code in the production branch is very out of date (it's using a manifest model from mattermost v5). So I went to the master branch, updated the model to a recent v6 from December, which has the changes we need (the "hosting" field), ran the code from there, and manually cut and pasted the json to a branch based on production. 
- I'll submit a pr to the marketplace in master, then we'll decide what to do to bring production up to speed. 
- cut with `/mb cutplugin --repo mattermost-plugin-calls --tag v0.12.0`
- this commit made with `go run ./cmd/generator/ add mattermost-plugin-calls v0.12.0 --official`
- https://mattermost.atlassian.net/browse/MM-49042

MM-49042 - Add v0.12.0 of mattermost-plugin-calls to the Marketplace

---

plugins.json

- NOTE: I had to do this kind of manually, again (see #332 and #333 )
- cut with `/mb cutplugin --repo mattermost-plugin-calls --tag v0.12.1`
- this commit made with `go run ./cmd/generator/ add mattermost-plugin-calls v0.12.1 --official`
- https://mattermost.atlassian.net/browse/MM-49638

MM-49638 - Add v0.12.1 of mattermost-plugin-calls to the Marketplace

---

cmd/generator/add.go
cmd/generator/main.go
internal/store/static.go

A plugin that makes use of an update in the manifest struct in the server will cause issues if it is added to the Marketplace as the Marketplace code is unaware of the struct update. https://github.com/mattermost/mattermost-marketplace/pull/332  is an example of that.
Allow the plugins with an invalid manifest in the Marketplace, but warn about them.
https://mattermost.atlassian.net/browse/MM-50329

[MM-50329] Allow adding plugins with an invalid manifest to the Marketplace

---

plugins.json

- NOTE: I had to do this kind of manually, yet again (see #337  )
- cut with `/mb cutplugin --repo mattermost-plugin-calls --tag v0.13.0`
- this commit made with `go run ./cmd/generator/ add mattermost-plugin-calls v0.13.0 --official`
- https://mattermost.atlassian.net/browse/MM-49679

MM-49679 - Add v0.13.0 of mattermost-plugin-calls to the Marketplace

---

.circleci/config.yml

By using Node 12 serverless@"<2.0.0" can be installed again.
Please note the successful CI test run in https://github.com/mattermost/mattermost-marketplace/commit/a33ddb4f217bbd65708c3f93973f24c65f2cb31f.
Fixes https://mattermost.atlassian.net/browse/MM-50203

Downgrade node version to 12

---

Makefile
internal/api/health_check_test.go

`git describe` tries to find a tag on the current branch. Tags are created on `master`. Given that `master` and `production` are distinct branches, the command needs to look at `master` instead of the current branch.
None

Always pull tags from master

---

plugins.json

- NOTE: I had to do this kind of manually, again (see #337)
- cut with `/mb cutplugin --repo mattermost-plugin-calls --tag v0.14.0`
- this commit made with `go run ./cmd/generator/ add mattermost-plugin-calls v0.14.0 --official`
- https://mattermost.atlassian.net/browse/MM-50566

MM-50566 - Add mattermost plugin calls v0.14.0

---

plugins.json

- dot release to fix a bad bug in the recorder
- cut with `/mb cutplugin --tag v0.14.1 --repo mattermost-plugin-calls --commitSHA 740ed9fcbde317205b618ab37223f1d13d39557f`
- this commit made with `go run ./cmd/generator/ add mattermost-plugin-calls v0.14.1 --official`
- There are some other lines that the generator fixed, that's because of the recent master->production merge. Let's commit those here so other plugins don't have to.
- none

Add v0.14.1 of mattermost-plugin-calls to the Marketplace

---

plugins.json

We've tested out the plugin on community and have not found any blocking issues for production approval https://community.mattermost.com/private-core/pl/rik7qg8g57nrtd9fe54exp7hso.
Further improvement requests have been ticketed here https://github.com/cpanato/mattermost-plugin-alertmanager/issues/174

Remove beta label for AlertManager plugin

---

internal/api/health_check.go
internal/api/label.go
plugins.json

- cut with `/mb cutplugin --repo mattermost-plugin-calls --tag v0.15.0`
- this commit made with `go run ./cmd/generator/ add mattermost-plugin-calls v0.15.0 --official`
- https://mattermost.atlassian.net/browse/MM-51461

MM-51461 - Add mattermost plugin calls v0.15.0

---

internal/api/health_check.go
internal/api/label.go

The CI checks on https://github.com/mattermost/mattermost-marketplace/pull/356 are currently failing due to a linting error regarding unused function parameter `r *http.Request`. This PR fixes the issue by using underscores to convey that this is not used.

Fix linting rule: Use underscore to convey unused variable

---

plugins.json

- cut with `/mb cutplugin --repo mattermost-plugin-calls --tag v0.15.1`
- this commit made with `go run ./cmd/generator/ add mattermost-plugin-calls v0.15.1 --official`
- none

Add v0.15.1 of mattermost-plugin-calls to the Marketplace

---

plugins.json

- cut with `/mb cutplugin --repo mattermost-plugin-calls --tag v0.16.0`
- this commit made with `go run ./cmd/generator/ add mattermost-plugin-calls v0.16.0 --official`
- https://mattermost.atlassian.net/browse/MM-52169

Add v0.16.0 of mattermost-plugin-calls to the Marketplace

---

plugins.json

- cut with `/mb cutplugin --repo mattermost-plugin-calls --tag v0.16.1`
- this commit made with `go run ./cmd/generator/ add mattermost-plugin-calls v0.16.1 --official`
- https://mattermost.atlassian.net/browse/MM-52936

MM-52936 - Add v0.16.1 of mattermost-plugin-calls to the Marketplace

---

plugins.json

- cut with `/mb cutplugin --repo mattermost-plugin-calls --tag v0.17.0`
- this commit made with `go run ./cmd/generator/ add mattermost-plugin-calls v0.17.0 --official`
- https://mattermost.atlassian.net/browse/MM-52800

MM-52800 - Add v0.17.0 of mattermost-plugin-calls to the Marketplace

---

plugins.json

Removes `mattermost-plugin-antivirus` and `mattermost-plugin-welcomebot` from Cloud listings. E.g. https://api.integrations.mattermost.com/api/v1/plugins?server_version=8.1.0&page=0&per_page=500&cloud=true&enterprise_plugins=true

Removes antivirus-v1.0.0 and welcomebot-v1.3.0 from Cloud listings

---

plugins.json

- cut with `/mb cutplugin --tag v0.19.0 --repo mattermost-plugin-calls`
- this commit made with `go run ./cmd/generator/ add mattermost-plugin-calls v0.19.0 --official`
- https://mattermost.atlassian.net/browse/MM-54176

MM-54176 - Add v0.19.0 of mattermost-plugin-calls to the Marketplace

---

plugins.json

- cut with `/mb cutplugin --repo mattermost-plugin-calls --tag v0.20.0`
- this commit made with `go run ./cmd/generator/ add mattermost-plugin-calls v0.20.0 --official`
- https://mattermost.atlassian.net/browse/MM-54508

Add v0.20.0 of mattermost-plugin-calls to the Marketplace

---

plugins.json

- cut with `/mb cutplugin --repo mattermost-plugin-calls --tag v0.21.0`
- this commit made with `go run ./cmd/generator/ add mattermost-plugin-calls v0.21.0 --official`
- https://mattermost.atlassian.net/browse/MM-54508

Add v0.21.0 of mattermost-plugin-calls to the Marketplace

---

.github/workflows/build-and-deploy.yml

Quickfix for https://github.com/mattermost/mattermost-marketplace/pull/393 : for the `build` workflow to run on non-master branch, we needed to create a local version of in in the checked-out repo, in order for the build scripts to work.
However, for workflows on `master` branch, the same command fails since the [master branch already exists](https://github.com/mattermost/mattermost-marketplace/actions/runs/6890904338/job/18744869517#step:4:5).
As a solution, we check if master branch exists, before attempting to create it.
https://mattermost.atlassian.net/browse/CLD-6549

Check for master branch existence before creating it, in build workflow

---

plugins.json

- cut with `/mb cutplugin --repo mattermost-plugin-calls --tag v0.21.1`
- this commit made with `go run ./cmd/generator/ add mattermost-plugin-calls v0.21.1 --official`
- https://mattermost.atlassian.net/browse/MM-55583

MM-55583 - Add v0.21.1 of mattermost-plugin-calls to the Marketplace

---

.github/workflows/build-and-deploy.yml

Increase verbosity of the `serverless` function, and store the deployment artifact, for better debuggability.
https://mattermost.atlassian.net/browse/CLD-6708

CLD-6708 Increase serverless verbosity, persist lambda artifact

---

plugins.json

- cut with `/mb cutplugin --repo mattermost-plugin-calls --tag v0.22.0`
- this commit made with `go run ./cmd/generator/ add mattermost-plugin-calls v0.22.0 --official`
- https://mattermost.atlassian.net/browse/MM-56164

Add v0.22.0 of mattermost-plugin-calls to the Marketplace

---

plugins.json

- cut with `/mb cutplugin --repo mattermost-plugin-calls --tag v0.23.1`
- this commit made with `go run ./cmd/generator/ add mattermost-plugin-calls v0.23.1 --official`
- none

Add v0.23.1 of mattermost-plugin-calls to the Marketplace

---

plugins.json

- https://github.com/mattermost/mattermost-plugin-gitlab/pull/460

Add v1.8.1 of mattermost-plugin-gitlab to the Marketplace

---

plugins.json

- cut with `/mb cutplugin --repo mattermost-plugin-calls --tag v0.25.1`
- this commit made with `go run ./cmd/generator/ add mattermost-plugin-calls v0.25.1 --official`
- none

Add v0.25.1 of mattermost-plugin-calls to the Marketplace

---

plugins.json

- https://github.com/mattermost/mattermost-plugin-gitlab/pull/448 - Discussion of release is here, though the PR is closed due to releases being done with no version bumps now

Add v1.9.0 of mattermost-plugin-gitlab to the Marketplace

---

.github/workflows/notify-mm-blog.yml

Aligning the action with the breaking changes introduced under https://github.com/mattermost/action-mattermost-notify/pull/13
Context: https://community.mattermost.com/core/pl/yb9ei7obg7ntjr483dbo1j8yoo
https://mattermost.atlassian.net/browse/CLD-8100

[fix] CI notify-community-server

---

plugins.json

Releasing v1 on Marketplace. This is what's pre-packaged in MM v10.

Release Calls v1.0.1

---

.github/workflows/build-and-deploy.yml

The deploy step is currently [failing](https://github.com/mattermost/mattermost-marketplace/actions/runs/10904226898/job/30260222151) after https://github.com/mattermost/mattermost-marketplace/pull/457 went in because the expected file is not found. 
I don't really have a good way to test this, so I tried my best, but please let me know if you have any thoughts.

Update CI to work with new lambda artifact

---

.github/workflows/build-and-deploy.yml

Let's try again. Downloading artifacts deals with directories so we were getting some new errors.

Fix path of downloaded artifact
