.github/workflows/go.yml
Leverage `cedrickring/golang-action/go1.12@1.3.0` to automatically build and test the repository on a pull request.
=> Experiment with GitHub Actions

Makefile
This PR ads a `make run` target to allow the same workflow as on the MM server.
None
=> Add make run

.circleci/config.yml
Add context to deploy job
https://community-daily.mattermost.com/private-core/pl/p8t9je6oipr97dqfg5ub716n4o
=> Add context to deploy job

.circleci/config.yml
Customize the CircleCI build scripts to automate the deployment of the `private-beta` branch.
=> Automate deployment of the private-beta branch.

app-marketplace-v2-spec/tasks.md
=> Comments on Tasks

app-marketplace-v2-spec/architecture.md
Add comments on the architecture
None
=> Comments on Architecture

app-marketplace-v2-spec/commands.md
Add comments on the commands
None
=> Commands comments

.github/ISSUE_TEMPLATE/add_plugin.md
Update issue template base on the conversation linked below.
https://community.mattermost.com/core/pl/8waz19admtygxe3s13pdpufwre
=> Update issue template to make clear that plugins can be submitted as Beta

.github/ISSUE_TEMPLATE/add_plugin.md
Downstream https://github.com/mattermost/mattermost-developer-documentation/pull/691
=> Downstream https://github.com/mattermost/mattermost-developer-documentation/pull/691

CONTRIBUTING.md
Add a check of the license file to checklist
None
=> Add a check of the license file to checklist

internal/model/label.go
Should be `Enterprise E20 and Cloud`
https://community-daily.mattermost.com/core/pl/dkoeiduaqt84uqnx3haz5exr8e
=> Change EE label name

plugins.json
Update Incident Collaboration.
=> Add v1.9.1 of mattermost-plugin-incident-collaboration to the Marketplace

plugins.json
=> Add v0.5.0 of mattermost-plugin-apps to the Marketplace

plugins.json
Publish v1.12.0 of mattermost-plugin-incident-collaboration to the Marketplace
N/A
=> Add v1.12.0 of mattermost-plugin-incident-collaboration to the Marketplace

plugins.json
Fixes https://github.com/mattermost/mattermost-plugin-apps/issues/204
=> Add v0.7.0 of mattermost-plugin-apps to the Marketplace

plugins.json
Publish v1.13.1 of mattermost-plugin-incident-collaboration
=> Add v1.13.1 of mattermost-plugin-incident-collaboration to the Marketplace

plugins.json
Add v1.14.3 of Incident Collaboration to the marketplace.
N/A
=> Add v1.14.3 of mattermost-plugin-incident-collaboration to the Marketplace

plugins.json
=> Add v1.15.0 of mattermost-plugin-incident-collaboration to the Marketplace

plugins.json
Fixes https://github.com/mattermost/mattermost-marketplace/issues/159
=> Add v2.1.0 of mattermost-plugin-giphy-moussetc to the Marketplace

plugins.json
Publish Focalboard (Boards) v0.10.0 to the Marketplace
=> Add v0.10.0 of Focalboard to the Marketplace

plugins.json
Fixes https://github.com/mattermost/mattermost-plugin-todo/issues/128
=> Add v0.5.0 of mattermost-plugin-todo to the Marketplace

plugins.json
Publish Focalboard (Boards) v0.12.0 to the Marketplace
=> Add v0.12.1 of focalboard to the Marketplace

plugins.json
Fixes https://github.com/mattermost/mattermost-plugin-todo/issues/157
=> Add v0.5.1 of mattermost-plugin-todo to the Marketplace

plugins.json
Publish Focalboard (Boards) v0.14.0 to the Marketplace
=> Add v0.14.0 of focalboard to the Marketplace

plugins.json
Fixes https://github.com/mattermost/mattermost-plugin-jira/issues/845
=> Add v3.2.0 of mattermost-plugin-jira to the Marketplace

plugins.json
Publish Focalboard (Boards) v0.15.0 to the Marketplace
=> Add v0.15.0 of focalboard to the Marketplace

plugins.json
Fixes https://github.com/mattermost/mattermost-plugin-bitbucket/issues/46
=> Add v1.1.1 of mattermost-plugin-bitbucket to the Marketplace

plugins.json
Fixes https://github.com/mattermost/mattermost-plugin-github/issues/553
=> Add v2.1.1 of mattermost-plugin-github to the Marketplace

.github/workflows/notify-mm-blog.sh
Update icon URL from mattermost.org to mattermost.com
https://mattermost.atlassian.net/browse/MM-42444
=> Update icon URL from mattermost.org to mattermost.com

plugins.json
Fixes https://github.com/mattermost/mattermost-plugin-apps/issues/319
=> Add v1.0.1 of mattermost-plugin-apps to the Marketplace

internal/model/label.go
https://community-daily.mattermost.com/core/pl/opyuij6ib7gkmxywrdx1qqbcnc
Fixes https://github.com/mattermost/mattermost-marketplace/issues/274
=> Change "Enterprise and Cloud" label to "Professional/Enterprise"

plugins.json
Generated with `go run ./cmd/generator/ add mattermost-plugin-skype4business v0.3.0 --official --beta`
--
=> Add v0.3.0 of mattermost-plugin-skype4business to the Marketplace

plugins.json
Add Playbooks v1.28.2 to the marketplace to work around https://mattermost.atlassian.net/browse/MM-45296.
None.
=> Add Playbooks v1.28.2

plugins.json
Publish Focalboard (Boards) v0.15.0 to the Marketplace
=> Add v7.0.1 of focalboard to the Marketplace

plugins.json
This PR is for adding version `v1.4.1` of the Gitlab plugin to the Mattermost marketplace.
=> Add v1.4.1 of mattermost-plugin-gitlab to the Marketplace

plugins.json
Fixes https://github.com/mattermost/mattermost-plugin-autolink/issues/144
=> Add v1.3.0 of mattermost-plugin-autolink to the Marketplace

plugins.json
Fixes https://github.com/mattermost/mattermost-plugin-zoom/issues/274
=> Add v1.6.1 of mattermost-plugin-zoom to the Marketplace

plugins.json
Fixes https://github.com/mattermost/mattermost-plugin-github/issues/580
=> Add v2.1.2 of mattermost-plugin-github to the Marketplace

plugins.json
Fixes https://github.com/mattermost/mattermost-plugin-memes/issues/60
=> Add v1.5.0 of mattermost-plugin-memes to the Marketplace

internal/model/label.go
Original PR to master https://github.com/mattermost/mattermost-marketplace/pull/273
=> Cherrypick "Professional/Enterprise" label to Production (#273)

plugins.json
Installed:
Thanks @mickmister for the plugin! 
Fixes https://github.com/mattermost/mattermost-marketplace/issues/177
=> Add v0.1.0 of mattermost-plugin-default-theme to the Marketplace

plugins.json
Fixes https://github.com/mattermost/mattermost-marketplace/issues/239
=> Add v1.0.0 of mattermost-plugin-hackerone to the Marketplace

plugins.json
Release for https://github.com/mattermost/mattermost-plugin-msteams-meetings/pull/80
Fixes https://github.com/mattermost/mattermost-plugin-msteams-meetings/issues/82
=> Add v2.1.0 of mattermost-plugin-msteams-meetings to the Marketplace

plugins.json
Fixes https://github.com/mattermost/mattermost-plugin-todo/issues/178
=> Add v0.7.0 of mattermost-plugin-todo to the Marketplace

plugins.json
Fixes https://github.com/mattermost/mattermost-plugin-gitlab/issues/337
=> Add v1.6.0 of mattermost-plugin-gitlab to the Marketplace

plugins.json
Fixes https://github.com/mattermost/mattermost-plugin-apps/issues/378
=> Add v1.2.0 of mattermost-plugin-apps to the Marketplace

plugins.json
Fixes https://github.com/mattermost/mattermost-marketplace/issues/298
=> Add v1.5.0 of matterpoll to the Marketplace

.circleci/config.yml
- Update serverless, following the advice of: https://github.com/serverless/serverless/issues/11118
- https://mattermost.atlassian.net/browse/MM-50203
=> MM-50203 - Update serverless

plugins.json
The PR also include some indenting fixes caused by https://github.com/mattermost/mattermost-marketplace/pull/332 and https://github.com/mattermost/mattermost-marketplace/pull/336.
Fixes https://github.com/mattermost/mattermost-plugin-jira/issues/905
=> Add v3.2.3 of mattermost-plugin-jira to the Marketplace

plugins.json
https://github.com/mattermost/mattermost-plugin-jira/pull/917
=> Add v3.2.4 of mattermost-plugin-jira to the Marketplace

plugins.json
Part of https://github.com/mattermost/mattermost-plugin-apps/pull/450
=> Add v1.2.1 of mattermost-plugin-apps to the Marketplace

plugins.json
Part of https://github.com/mattermost/mattermost-plugin-autolink/pull/203
=> Add v1.4.0 of mattermost-plugin-autolink to the Marketplace

plugins.json
https://github.com/mattermost/mattermost-plugin-zoom/pull/292
=> Add v1.6.2 of mattermost-plugin-zoom to the Marketplace

plugins.json
https://github.com/mattermost/mattermost-plugin-github/pull/660
=> Add v2.1.5 of mattermost-plugin-github to the Marketplace

plugins.json
https://github.com/mattermost/mattermost-plugin-mscalendar/pull/255
=> Add v1.2.1 of mattermost-plugin-mscalendar to the Marketplace

plugins.json
github 2.1.6
Fixes https://mattermost.atlassian.net/browse/MM-52571
=> github v2.1.6

plugins.json
Release https://github.com/mattermost/mattermost-plugin-jira/releases
https://github.com/mattermost/mattermost-plugin-jira/pull/937
=> Add v3.2.5 of mattermost-plugin-jira to the Marketplace

plugins.json
https://github.com/mattermost/mattermost-plugin-welcomebot/pull/105
=> Add v1.3.0 of mattermost-plugin-welcomebot to the Marketplace

plugins.json
- https://github.com/mattermost/mattermost-plugin-gitlab/pull/300
- https://github.com/mattermost/mattermost-plugin-gitlab/pull/285
- https://github.com/mattermost/mattermost-plugin-gitlab/pull/307
- https://github.com/mattermost/mattermost-plugin-gitlab/pull/363
- https://github.com/mattermost/mattermost-plugin-gitlab/pull/365
- https://github.com/mattermost/mattermost-plugin-gitlab/pull/366
- https://github.com/mattermost/mattermost-plugin-gitlab/pull/369
- https://github.com/mattermost/mattermost-plugin-gitlab/pull/368
- https://github.com/mattermost/mattermost-plugin-gitlab/pull/364
- https://github.com/mattermost/mattermost-plugin-gitlab/pull/375
- https://github.com/mattermost/mattermost-plugin-gitlab/pull/308
- https://github.com/mattermost/mattermost-plugin-gitlab/pull/379 …
=> Add v1.7.0 of mattermost-plugin-gitlab to the Marketplace

plugins.json
- cut with `/mb cutplugin --tag v0.18.1 --repo mattermost-plugin-calls --commitSHA 5166bf5af1309b5ec04a6c27d5ceaf829051e879`
- this commit made with `go run ./cmd/generator/ add mattermost-plugin-calls v0.18.1 --official`
- https://mattermost.atlassian.net/browse/MM-54259
=> MM-54259 - Add mattermost-plugin-calls v0.18.1 to the marketplace

plugins.json
- cut with `/mb cutplugin --tag v0.18.2 --repo mattermost-plugin-calls --commitSHA a29ebe0ca2fc9ee645d6b8bbbf10132db2bcfad8 `
- this commit made with `go run ./cmd/generator/ add mattermost-plugin-calls v0.18.2 --official`
=> Add mattermost plugin calls v0.18.2 to the marketplace

plugins.json
https://github.com/mattermost/mattermost-plugin-jira/pull/966
=> Add v4.0.0 of mattermost-plugin-jira to the Marketplace

plugins.json
https://github.com/mattermost/mattermost-plugin-jira/pull/994
=> Add v4.0.1 of mattermost-plugin-jira to the Marketplace

.github/workflows/build-and-deploy.yml
This PR:
- Works around an open issue in `actions/upload-artifact`: https://github.com/actions/upload-artifact/issues/38
- Removes the final artifact-upload job, since serverless produces no artifact
I'll also test out deploy
https://mattermost.atlassian.net/browse/CLD-6708
=> Fix artifact path

.github/workflows/build-and-deploy.yml
This is a port of the fixes from https://github.com/mattermost/mattermost-marketplace/pull/403 to the `private-beta` branch
https://mattermost.atlassian.net/browse/CLD-6708
=> CLD-6708 Fix pipeline

plugins.json
- cut with `/mb cutplugin --repo mattermost-plugin-calls --tag v0.22.1`
- this commit made with `go run ./cmd/generator/ add mattermost-plugin-calls v0.22.1 --official`
- https://mattermost.atlassian.net/browse/MM-56178
=> MM-56178 - Add v0.22.1 of mattermost-plugin-calls to the Marketplace

plugins.json
- cut with `/mb cutplugin --repo mattermost-plugin-calls --tag v0.22.2`
- this commit made with `go run ./cmd/generator/ add mattermost-plugin-calls v0.22.2 --official`
- https://mattermost.atlassian.net/browse/MM-56273
=> MM-56273 - Add mattermost plugin calls v0.22.2

plugins.json
- cut with `/mb cutplugin --repo mattermost-plugin-calls --tag v0.23.0`
- this commit made with `go run ./cmd/generator/ add mattermost-plugin-calls v0.23.0 --official`
- https://mattermost.atlassian.net/browse/MM-56164
=> MM-56164 - Add mattermost plugin calls v0.23.0

plugins.json
- https://github.com/mattermost/mattermost-plugin-jira/pull/997
=> Add v4.1.0 of mattermost-plugin-jira to the Marketplace

plugins.json
- cut with `/mb cutplugin --repo mattermost-plugin-calls --tag v0.24.0`
- this commit made with `go run ./cmd/generator/ add mattermost-plugin-calls v0.24.0 --official`
- https://mattermost.atlassian.net/browse/MM-56571
=> MM-56571 - Add v0.24.0 of mattermost-plugin-calls to the Marketplace

plugins.json
- https://github.com/mattermost/mattermost-plugin-github/pull/709
=> Add v2.2.0 of mattermost-plugin-github to the Marketplace

plugins.json
- https://github.com/mattermost/mattermost-plugin-aws-SNS/pull/83
=> Add v1.3.0 of mattermost-plugin-aws-SNS to the Marketplace

plugins.json
- cut with `/mb cutplugin --repo mattermost-plugin-calls --tag v0.25.0`
- this commit made with `go run ./cmd/generator/ add mattermost-plugin-calls v0.25.0 --official`
- https://mattermost.atlassian.net/browse/MM-56892
=> MM-56892 - Add v0.25.0 of mattermost-plugin-calls to the Marketplace

plugins.json
add mattermost-plugin-msteams v1.10.0
=> add mattermost-plugin-msteams v1.10.0

plugins.json
add mattermost-plugin-msteams v1.10.2
=> add mattermost-plugin-msteams v1.10.2

plugins.json
add mattermost-plugin-msteams v1.11.0
=> add mattermost-plugin-msteams v1.11.0

plugins.json
add mattermost-plugin-msteams v1.11.1
=> add mattermost-plugin-msteams v1.11.1

plugins.json
=> add mattermost-plugin-msteams v1.12.1

plugins.json
=> add mattermost-plugin-msteams v1.12.2

plugins.json
add mattermost-plugin-msteams v1.12.3
=> add mattermost-plugin-msteams v1.12.3

plugins.json
- https://github.com/mattermost/mattermost-plugin-zoom/issues/371
- https://community.mattermost.com/core/channels/release-zoom-200
=> Add v1.8.0 of mattermost-plugin-zoom to the Marketplace

plugins.json
Update mattermost-plugin-msteams v1.13.0
=> add mattermost-plugin-msteams v1.13.0

plugins.json
- cut with `/mb cutplugin --repo mattermost-plugin-calls --tag v0.27.0`
- this commit made with `go run ./cmd/generator/ add mattermost-plugin-calls v0.27.0 --official`
- https://mattermost.atlassian.net/browse/MM-57857
=> [MM-57857] Add v0.27.0 of mattermost-plugin-calls to the Marketplace

plugins.json
https://github.com/mattermost/mattermost-plugin-gitlab/issues/496
=> Add v1.9.1 of mattermost-plugin-gitlab to the Marketplace

plugins.json
- cut with `make minor`
- this commit made with `go run ./cmd/generator/ add mattermost-plugin-calls v0.28.1 --official`
- https://mattermost.atlassian.net/browse/MM-58296
=> [MM-58296] Update prepackage calls to v0.28.1

plugins.json
Updating the signatures with the correct ones.
Fixes https://github.com/mattermost/mattermost-plugin-calls/issues/788
https://mattermost.atlassian.net/browse/MM-58833
=> [MM-58833] Fix Calls v0.28.1 release signature

plugins.json
- cut with `make patch`
- this commit made with `go run ./cmd/generator/ add mattermost-plugin-calls v0.28.2 --official`
- https://mattermost.atlassian.net/browse/MM-59037
=> [MM-59037] Add v0.28.2 of mattermost-plugin-calls to the Marketplace

plugins.json
-https://community.mattermost.com/core/channels/release-github-230
=> Add v2.3.0 of mattermost-plugin-github to the Marketplace

plugins.json
- cut with `make patch`
- this commit made with `go run ./cmd/generator/ add mattermost-plugin-calls v0.29.0 --official`
- https://mattermost.atlassian.net/browse/MM-58750
=> [MM-58750] Add v0.27.0 of mattermost-plugin-calls to the Marketplace

plugins.json
- cut with `make patch`
- this commit made with `go run ./cmd/generator/ add mattermost-plugin-calls v0.29.1 --official`
- none
=> Add v0.29.1 of mattermost-plugin-calls to the Marketplace

.github/workflows/notify-mm-blog.yml
Cherry-pick https://github.com/mattermost/mattermost-marketplace/pull/449
https://mattermost.atlassian.net/browse/CLD-8100
=> [CLD-8100] [fix] CI notify-community-server

plugins.json
Add mattermost-plugin-msteams-sync v2.0.3 to the marketplace.
Relates-to: https://mattermost.atlassian.net/browse/MM-59485
=> add mattermost-plugin-msteams-sync v2.0.3

.github/workflows/notify-mm-blog.yml
Inputing the output of `mattermost.json` to the PAYLOAD input of the notify action.
Builds on https://github.com/mattermost/mattermost-marketplace/pull/449#issuecomment-2286027219
=> [fix] CI Notification

.github/workflows/build-and-deploy.yml
=> fix: Never forget to checkout
